# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4b81f73824b813bd0a5124919bd71a30"
name = "customapp002"
handle = "customapp002"
application_url = "https://uploaded-smoking-targeted-crossword.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "chandan-test-store-1.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "read_orders,read_products"

[auth]
redirect_urls = [
  "https://uploaded-smoking-targeted-crossword.trycloudflare.com/auth/callback",
  "https://uploaded-smoking-targeted-crossword.trycloudflare.com/auth/shopify/callback",
  "https://uploaded-smoking-targeted-crossword.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-07"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks"

[pos]
embedded = false
